//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalkboard.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityEntryComment
    {
        public int Id { get; set; }
        public int ActivityEntriesId { get; set; }
        public int UserId { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ActivityEntry ActivityEntry { get; set; }
        public virtual User User { get; set; }
    }
}
